export const ADD_PERSON = 'ADD_PERSON';
export const ADD_PEOPLE = 'ADD_PEOPLE';
export const REQUEST_PEOPLE = 'REQUEST_PEOPLE';
export const FETCH_PEOPLE = 'FETCH_PEOPLE';
export const RECIEVE_PEOPLE = 'RECIEVE_PEOPLE';